<?php
/**
 * Created by PhpStorm.
 * User: Md. Al-Mahmud
 * Date: 12/22/2019
 * Time: 5:06 PM
 */


return [

    /*
    |--------------------------------------------------------------------------
    |  Role Manage
    |--------------------------------------------------------------------------
    */

    'User' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],

    'RoleManager' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'Settings' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'Project' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'LedgerType' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'LedgerGroup' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'LedgerName' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'BankCash' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'InitialIncomeExpenseHeadBalance' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'InitialBankCashBalance' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'DrVoucher' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'CrVoucher' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'JnlVoucher' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'ContraVoucher' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],


    'Ledger' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'TrialBalance' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'CostOfRevenue' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'ProfitOrLossAccount' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'RetainedEarning' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'FixedAssetsSchedule' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'StatementOfFinancialPosition' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'CashFlow' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'ReceiveAndPayment' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'Notes' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'GeneralBranch' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'GeneralLedger' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'GeneralBankCash' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'GeneralVoucher' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],


    // Inventory

    'Product' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'Sell' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'PurchaseRequisition' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'PurchaseRQNConfirm' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'PurchaseOrder' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'Vendor' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'Employee' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'Customer' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'PurchaseReport' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],
    'SellsReport' => [
        'All' => 1,
        'Create' => 1,
        'Delete' => 1,
        'Edit' => 1,
        'Pdf' => 1,
        'PermanentlyDelete' => 1,
        'Restore' => 1,
        'Show' => 1,
        'TrashShow' => 1,
    ],


];

